---
repos:
  - repo: https://github.com/ansible-community/ansible-lint.git
    rev: v6.12.2
    hooks:
    # Note this is set with 'always_run' true; so our file/excludes mean nothing
      - id: ansible-lint
        # files: \.(yaml|yml)$
        # exclude: (github/workflows/|pre-commit-config)

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
        exclude: (\.md|\.csv|.bumpversion\.cfg)$
      - id: end-of-file-fixer
        exclude: (\.md|\.csv|.bumpversion\.cfg)$
      - id: check-ast
      - id: check-yaml
      - id: check-added-large-files
        args: ["--maxkb=200"]
      - id: check-merge-conflict
      - id: detect-private-key
      - id: mixed-line-ending
        args: ["--fix=lf"]

  - repo: https://github.com/PyCQA/isort.git
    rev: "5.12.0"
    hooks:
      - id: isort

  - repo: https://github.com/pre-commit/mirrors-autopep8
    rev: v2.0.1
    hooks:
      - id: autopep8
