---
# Install runtime dependencies for cdillc.splunk

- name: Install dependencies for controller
  hosts: localhost
  become: false
  tasks:
    - name: Install Python dependencies for the 'cdillc.splunk' collection
      ansible.builtin.pip:
        requirements: "{{ playbook_dir }}/files/requirements.txt"
        extra_args: "--upgrade"


- name: Install dependencies for splunk hosts
  hosts: "{{ splunk_host | default('all') }}"
  tasks:
    - name: Copy requirements file
      ansible.builtin.copy:
        src: "{{ playbook_dir }}/files/requirements.txt"
        dest: "/tmp/cdillc-splunk-requirements.txt"
        mode: "0640"

    - name: Install Python dependencies for the 'cdillc.splunk' collection
      ansible.builtin.pip:
        requirements: /tmp/cdillc-splunk-requirements.txt
        extra_args: "--upgrade"
        virtualenv: "{{ venv_location | default(omit) }}"
        virtualenv_command: "{{ ansible_python_interpreter }} -m venv"
